services:
  Jycamier\MessengerProcessBundle\Task\:
    resource: '../../../Task/*'
    autowire: true
    public: true
    shared: false
    tags:
      - { name: monolog.logger, channel: cleverage_process_task }
